In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
#one hot Representation
one_hot_rp=[one_hot(words,voc_size)for words in sent]
one_hot_rp

[[6119, 760, 5825, 1497],
 [6119, 760, 5825, 7695],
 [6119, 2342, 5825, 7575],
 [1457, 6235, 6556, 6992, 229],
 [1457, 6235, 6556, 6992, 5750],
 [1639, 6119, 31, 5825, 5431],
 [2083, 9482, 1619, 6992]]

In [6]:
## word embedding representations

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rp,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 6119,  760, 5825, 1497],
       [   0,    0,    0,    0, 6119,  760, 5825, 7695],
       [   0,    0,    0,    0, 6119, 2342, 5825, 7575],
       [   0,    0,    0, 1457, 6235, 6556, 6992,  229],
       [   0,    0,    0, 1457, 6235, 6556, 6992, 5750],
       [   0,    0,    0, 1639, 6119,   31, 5825, 5431],
       [   0,    0,    0,    0, 2083, 9482, 1619, 6992]])

In [9]:
#feature reprentation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 80ms/step


array([[[-1.10634938e-02, -2.34337337e-02,  1.03195421e-02,
          3.41413133e-02, -2.62871981e-02,  1.21372938e-03,
         -2.03559548e-03, -4.28187735e-02,  3.80990021e-02,
         -1.06040128e-02],
        [-1.10634938e-02, -2.34337337e-02,  1.03195421e-02,
          3.41413133e-02, -2.62871981e-02,  1.21372938e-03,
         -2.03559548e-03, -4.28187735e-02,  3.80990021e-02,
         -1.06040128e-02],
        [-1.10634938e-02, -2.34337337e-02,  1.03195421e-02,
          3.41413133e-02, -2.62871981e-02,  1.21372938e-03,
         -2.03559548e-03, -4.28187735e-02,  3.80990021e-02,
         -1.06040128e-02],
        [-1.10634938e-02, -2.34337337e-02,  1.03195421e-02,
          3.41413133e-02, -2.62871981e-02,  1.21372938e-03,
         -2.03559548e-03, -4.28187735e-02,  3.80990021e-02,
         -1.06040128e-02],
        [-3.41857821e-02, -3.06901094e-02, -2.02567466e-02,
         -3.43308821e-02,  3.96316759e-02,  2.65173353e-02,
         -3.69712487e-02, -1.57860294e-02, -1.093095

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6119,  760, 5825, 1497])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.01106349, -0.02343373,  0.01031954,  0.03414131, -0.0262872 ,
         0.00121373, -0.0020356 , -0.04281877,  0.038099  , -0.01060401],
       [-0.01106349, -0.02343373,  0.01031954,  0.03414131, -0.0262872 ,
         0.00121373, -0.0020356 , -0.04281877,  0.038099  , -0.01060401],
       [-0.01106349, -0.02343373,  0.01031954,  0.03414131, -0.0262872 ,
         0.00121373, -0.0020356 , -0.04281877,  0.038099  , -0.01060401],
       [-0.01106349, -0.02343373,  0.01031954,  0.03414131, -0.0262872 ,
         0.00121373, -0.0020356 , -0.04281877,  0.038099  , -0.01060401],
       [-0.03418578, -0.03069011, -0.02025675, -0.03433088,  0.03963168,
         0.02651734, -0.03697125, -0.01578603, -0.01093096, -0.04820039],
       [ 0.01425711,  0.03794864,  0.01902724,  0.00654117,  0.02643813,
        -0.02117899, -0.02130498, -0.01054639,  0.01981512, -0.02900776],
       [ 0.03962871, -0.01300403,  0.0125141 , -0.00135722,  0.04513777,
        -0.01756625, -0.01096543, -0.02597376